import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "app/store";
import { fetchCount } from "./counterAPI";

export interface CounterState {
  value: number;
  status: "idle" | "loading" | "failed";
}

const initialState: CounterState = {
  value: 0,
  status: "idle",
};

const PREFIX = "counter";

// 아래 함수는 thunk를 호출하여 비동기적 로직을 수행하도록 한다.
// 일반적인 action 과 같이 dispatch 될수 있다. ex) dispatch(incrementAsync(10))
// thunk를 dispatch 함수와 함께 첫번째 인자로 호출한다.
// 그리고 나서 비동기 코드가 실행되고 다른 action 이 dispatch 된다.
// Thunks 는 대개 비동기 요청을 위해 사용된다.
export const incrementAsync = createAsyncThunk(
  `${PREFIX}/fetchCount`,
  async (amount: number) => {
    const response = await fetchCount(amount);
    return response.data; // return 값은 fulfilled 시 action의 payload 값이 된다. (A)
  }
);

/*
// the outside "thunk creator" function
const fetchUserById = userId => {
  // the inside "thunk function"
  return async (dispatch, getState) => {
    try {
      // make an async call in the thunk
      const user = await userAPI.fetchById(userId)
      // dispatch an action when we get the response back
      dispatch(userLoaded(user))
    } catch (err) {
      // If something went wrong, handle it here
    }
  }
}
*/

// createAction + createReducer
export const counterSlice = createSlice({
  name: PREFIX, // action type의 prefix, ex) counter/increment...
  initialState,
  reducers: {
    // reducers 필드로 리듀서를 정의하고 관련 action을 생성, counterSlice.actions
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action: PayloadAction<number>) => {
      // state.value = 이전 상태값
      // action = {type: 'counter/incrementByAmount', payload: Counter input 값}
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(incrementAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(incrementAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.value += action.payload; // (A)
      })
      .addCase(incrementAsync.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectCount = (state: RootState) => state.counter.value;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
export const incrementIfOdd =
  (amount: number): AppThunk =>
  (dispatch, getState) => {
    // dispatch(action) : 순수 자바스크립트 객체로 액션을 내보냄, 상태 변경할 수 있는 유일한 방법
    // getState() : 애플리케이션의 현재 상태 트리 반환
    const currentValue = selectCount(getState());
    if (currentValue % 2 === 1) {
      dispatch(incrementByAmount(amount));
    }
  };

export default counterSlice.reducer;
